package Oficinapp;


/**
* Oficinapp/InterfazHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaz.idl
* miércoles 12 de mayo de 2021 10:53:59 PM CDT
*/

abstract public class InterfazHelper
{
  private static String  _id = "IDL:Oficinapp/Interfaz:1.0";

  public static void insert (org.omg.CORBA.Any a, Oficinapp.Interfaz that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Oficinapp.Interfaz extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Oficinapp.InterfazHelper.id (), "Interfaz");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Oficinapp.Interfaz read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_InterfazStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Oficinapp.Interfaz value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Oficinapp.Interfaz narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Oficinapp.Interfaz)
      return (Oficinapp.Interfaz)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Oficinapp._InterfazStub stub = new Oficinapp._InterfazStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Oficinapp.Interfaz unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Oficinapp.Interfaz)
      return (Oficinapp.Interfaz)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Oficinapp._InterfazStub stub = new Oficinapp._InterfazStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
