package Oficinapp;


/**
* Oficinapp/Interfaz.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaz.idl
* miércoles 12 de mayo de 2021 10:53:59 PM CDT
*/

public interface Interfaz extends InterfazOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interfaz
