package Oficinapp;


/**
* Oficinapp/InterfazPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaz.idl
* miércoles 12 de mayo de 2021 10:53:59 PM CDT
*/

public abstract class InterfazPOA extends org.omg.PortableServer.Servant
 implements Oficinapp.InterfazOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("pago", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Oficinapp/Interfaz/pago
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.pago (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Oficinapp/Interfaz/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Oficinapp/Interfaz:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Interfaz _this() 
  {
    return InterfazHelper.narrow(
    super._this_object());
  }

  public Interfaz _this(org.omg.CORBA.ORB orb) 
  {
    return InterfazHelper.narrow(
    super._this_object(orb));
  }


} // class InterfazPOA
