package Oficinapp;

/**
* Oficinapp/InterfazHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interfaz.idl
* miércoles 12 de mayo de 2021 10:53:59 PM CDT
*/

public final class InterfazHolder implements org.omg.CORBA.portable.Streamable
{
  public Oficinapp.Interfaz value = null;

  public InterfazHolder ()
  {
  }

  public InterfazHolder (Oficinapp.Interfaz initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Oficinapp.InterfazHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Oficinapp.InterfazHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Oficinapp.InterfazHelper.type ();
  }

}
